# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - deiafrica

on:
  push:
    branches:
      - main
      - feature/coderabbit-setup
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '24.x'

      - name: Create deployment package
        run: |
          zip -r deploy.zip . \
            --exclude "*.git*" \
            --exclude "node_modules/*" \
            --exclude "server/node_modules/*" \
            --exclude "dist/*"

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_5C2345BD2338497CB446DEDAC724C0CF }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_12DD5DFE38C24744B7CA3FDA00D7D1B5 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_7FF3B173AAD94AAFB71332D2B833A454 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'deiafrica'
          slot-name: 'Production'
          package: deploy.zip
          startup-command: 'node server/server.js'
